#!/usr/bin/env python3
"""MPM(multiple process manager) — 서비스 레지스트리 + Procfile 생성기 + 백그라운드 관리자.

단일 소스(SERVICES)에서 honcho Procfile 을 결정적으로 생성·검증하고, 전 프로세스를
백그라운드(detached)로 일괄 기동·중지·상태조회한다. 표준 라이브러리만 사용.
사용:
  python3 tools/mpm/mpm.py --env dev                 # Procfile → stdout
  python3 tools/mpm/mpm.py --env local --group py    # python 서비스만
  python3 tools/mpm/mpm.py --check                   # 생성물 검증(유효 0, 무효 1)
  python3 tools/mpm/mpm.py up --env dev              # 백그라운드 일괄 기동(detached + 로그·pid)
  python3 tools/mpm/mpm.py status                    # 실행 상태
  python3 tools/mpm/mpm.py stop                      # 전 프로세스 종료(프로세스 그룹)
"""
import argparse
import os
import re
import signal
import subprocess
import sys

MPM_DIR = ".mpm"  # cwd(레포 루트) 기준 상태 디렉터리

# 서비스 레지스트리 — name, group, cwd, 포트(있으면), cmd 템플릿({env} 치환).
SERVICES = [
    {"name": "ingest", "group": "py", "port": 8003,
     "cmd": "cd services/ingest && APP_ENV={env} uv run uvicorn app.main:app --reload --port 8003"},
    {"name": "analysis", "group": "py", "port": 8001,
     "cmd": "cd services/analysis && APP_ENV={env} uv run uvicorn app.main:app --reload --port 8001"},
    {"name": "rag", "group": "py", "port": 8002,
     "cmd": "cd services/rag && APP_ENV={env} uv run uvicorn app.main:app --reload --port 8002"},
    {"name": "agents", "group": "py", "port": 8004,
     "cmd": "cd services/agents && APP_ENV={env} uv run uvicorn app.main:app --reload --port 8004"},
    {"name": "risk", "group": "rust", "port": 3001,
     "cmd": "bash -c 'set -a; . ./.env.{env}; set +a; cd core/risk-engine && cargo run'"},
    {"name": "web", "group": "web", "port": 3000,
     "cmd": "bash -c 'set -a; . ./.env.{env}; set +a; cd web && pnpm -r dev'"},
]

GROUPS = sorted({s["group"] for s in SERVICES})       # py | rust | web
_LINE_RE = re.compile(r"^[a-z0-9_-]+:\s+\S")          # honcho 프로세스 라인


def services_for(groups=None):
    """그룹 필터 — None/빈 = 전체. 알 수 없는 그룹은 ValueError."""
    if not groups:
        return list(SERVICES)
    unknown = [g for g in groups if g not in GROUPS]
    if unknown:
        raise ValueError(f"unknown group(s): {unknown}. valid: {GROUPS}")
    return [s for s in SERVICES if s["group"] in set(groups)]


def render_procfile(env="local", groups=None):
    """ENV·그룹별 Procfile 텍스트 생성(결정적, 레지스트리 순서 보존)."""
    header = f"# generated by tools/mpm — env={env} groups={','.join(groups) if groups else 'all'}"
    lines = [header]
    for s in services_for(groups):
        lines.append(f"{s['name']}: {s['cmd'].format(env=env)}")
    return "\n".join(lines) + "\n"


def validate(text):
    """Procfile 유효성 — 비어있지 않은 비주석 라인이 모두 `name: cmd` 형식이어야 True."""
    procs = [ln for ln in text.splitlines() if ln.strip() and not ln.lstrip().startswith("#")]
    if not procs:
        return False
    return all(_LINE_RE.match(ln) for ln in procs)


# ── 백그라운드 관리(supervisor) — 상태는 cwd 기준 .mpm/ ──

def procfile_path():
    return os.path.join(MPM_DIR, "Procfile.gen")


def pidfile_path():
    return os.path.join(MPM_DIR, "mpm.pid")


def logfile_path():
    return os.path.join(MPM_DIR, "mpm.log")


def read_pid():
    """pidfile 의 pid(int) 또는 None."""
    try:
        with open(pidfile_path()) as f:
            return int(f.read().strip())
    except (OSError, ValueError):
        return None


def pid_alive(pid):
    """프로세스 생존 여부 — signal 0 probe. EPERM(권한)도 생존으로 간주."""
    if not pid or pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def up(env="local", groups=None):
    """전 프로세스 백그라운드 기동 — honcho 를 detached 세션으로 실행(로그·pid 기록)."""
    if pid_alive(read_pid()):
        print(f"mpm already running (pid {read_pid()})", file=sys.stderr)
        return 1
    os.makedirs(MPM_DIR, exist_ok=True)
    with open(procfile_path(), "w") as f:
        f.write(render_procfile(env, groups))
    log = open(logfile_path(), "ab")
    proc = subprocess.Popen(
        ["uvx", "--from", "honcho", "honcho", "-f", procfile_path(), "start"],
        stdout=log, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
        start_new_session=True,  # 자체 프로세스 그룹 → 일괄 종료 가능
    )
    with open(pidfile_path(), "w") as f:
        f.write(str(proc.pid))
    print(f"mpm started (pid {proc.pid}, env={env}, groups={','.join(groups) if groups else 'all'})")
    print(f"  logs: tail -f {logfile_path()}   stop: make mpm-stop")
    return 0


def stop(grace=8.0):
    """전 프로세스 종료 — honcho 에 SIGTERM(각 자식 프로세스그룹 graceful 종료) →
    잔여(detach 된 next dev 워커 등) 프로세스그룹 일괄 SIGTERM 으로 정리.
    """
    import time

    pid = read_pid()
    if not pid_alive(pid):
        print("mpm not running")
        if pid is not None:
            try:
                os.remove(pidfile_path())
            except OSError:
                pass
        return 0
    # 1) honcho graceful — 자체 관리 프로세스(그룹)들을 순차 종료.
    try:
        pgid = os.getpgid(pid)
    except ProcessLookupError:
        pgid = None
    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
    # honcho 종료 대기(graceful cascade).
    deadline = time.monotonic() + grace
    while pid_alive(pid) and time.monotonic() < deadline:
        time.sleep(0.2)
    # 2) 잔여 정리 — 세션 프로세스그룹 일괄 SIGTERM(escape 한 워커 포함).
    if pgid is not None:
        try:
            os.killpg(pgid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError):
            pass
    try:
        os.remove(pidfile_path())
    except OSError:
        pass
    print(f"mpm stopped (pid {pid})")
    return 0


def status():
    pid = read_pid()
    if pid_alive(pid):
        print(f"running (pid {pid})")
    else:
        print("stopped")
    return 0


def main(argv=None):
    p = argparse.ArgumentParser(description="MPM — Procfile generator + background manager")
    p.add_argument("action", nargs="?", default="gen", choices=["gen", "up", "stop", "status"],
                   help="gen(기본, Procfile→stdout) | up(백그라운드 기동) | stop | status")
    p.add_argument("--env", default="local")
    p.add_argument("--group", action="append", help="서비스 그룹(py|rust|web), 반복 가능. 미지정=전체")
    p.add_argument("--check", action="store_true", help="gen 검증만(출력 없음, exit code)")
    args = p.parse_args(argv)

    if args.action == "stop":
        return stop()
    if args.action == "status":
        return status()
    try:
        if args.action == "up":
            return up(args.env, args.group)
        text = render_procfile(args.env, args.group)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    if args.check:
        return 0 if validate(text) else 1
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
